### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by erikluckycraft** [GC-spigot/AdvancedItems#1]
Recap:

- Set bonus does not work anymore.
- Conditions like this does not work anymore: conditions: '%block type% contains log : %allow%', they now have to be at lines for some reason like summer config.
- Kill_mob does not work on a bow
- Chest broken with some AI axes don't drop stuff anymore
- This condition does not work anymore:       - '%block type% = SAND && %offhand item% = TORCH : %allow%' after recent update
- If %block type% contains DEEPSLATE and you have an effect of MORE_DROPS:1, it does not work. (MORE_DROPS) in general does not work.
- GUARD with target @Victim is not valid. 

**- Chests broken with AI items don't drop the items anymore config.**
Config:
Example Item
item:
  type: NETHERITE_AXE
  amount: 1
  name: '&x&f&f&d&7&0&0&l&nZ&x&f&c&c&3&0&c&l&nO&x&f&9&a&f&1&8&l&nM&x&f&6&9&b&2&3&l&nE&x&f&3&8&7&2&f&l&nR&x&f&f&d&7&0&0&l AXE'
  lore:
  - '&f'
  - '{#FFD700}☀ Zomer Crate 2023'
  - '&f'
  - '{#F9EA9A}⚔ Speciale kracht:'
  - '{#DADADA}Je hebt 5% kans om meer'
  - '{#DADADA}logs te krijgen.'
  enchantments:
  - 'unbreaking:5'
  - 'efficiency:6'
  - 'mending:1'
  MINING:
    conditions: 
      - "%block type% contains LOG : %allow%"
    chance: 5
    effects:
      - 'MORE_DROPS:1'
- **KILL MOB does not work with a bow config**
`  KILL_MOB:
    chance: 100  
    effects:  
      - 'CONSOLE_COMMAND:money give %player name% <random number>1-5</random number> <chance>5</chance>'
      - 'EXP:1 @Attacker <chance>5</chance>'     
      - 'MESSAGE:&ATEST BERICHT, SUCCES'

**Comment by GC-spigot** [comment]
- Tested set bonuses - they work well
- Conditions have been reworked with new abilities and they must be in lines yes
- Fixed
- Chests do break stuff now
- Etc

Seems like most if not all are resolved, Ill test everything else
