### ISSUE TITLE
PLEASE FIX FAST

### ISSUE THREAD

**Issue by egssens** [GC-spigot/AdvancedItems#19]
It's been two weeks. Please fix the dupe glitch where you can place blocks and mine them again and it activates again.

TYPE: MINING

MORE_DROPS:2

ISSUE: PLACED BLOCKS BY THE PLAYERS CAN BE DUPLICATED THIS WAY. (!)

**Comment by SirJben** [comment]
Will reforward it, please don't make duplicate [issue](https://github.com/GC-spigot/AdvancedItems/issues/14)

**Comment by SirJben** [comment]
Will reforward it, please don't make duplicate [issue](https://github.com/GC-spigot/AdvancedItems/issues/14)
