### ISSUE TITLE
Leather armor cannot be used in items

### ISSUE THREAD

**Issue by pjindras** [GC-spigot/AdvancedItems#2]
Hello, it is not possible to use leather armor as advanced item, which causes issues with Itemadder.

![image (1)](https://github.com/GC-spigot/AdvancedItems/assets/45400186/db4fb480-d7a9-47ae-a595-bffe35284bde)
![image](https://github.com/GC-spigot/AdvancedItems/assets/45400186/cc82a142-27e1-4a55-a35c-afcba0f1a96c)

We have lastest version of advanceditems.

**Comment by petrkeram** [comment]
I have a same problem...

@GC-spigot can you help us? I see you relased new version to support 1.20.2 but we need this 😁 thanks

**Comment by Kleit02** [comment]
I have the same problem, I will have to wait for them to repair it...

**Comment by petrkeram** [comment]
> I have the same problem, I will have to wait for them to repair it...

I was informed that they knows about the problems... but the question is, if they will ever fix it...

**Comment by petrkeram** [comment]
I see another problem :)
If i set diamond sword to item with model (ItemAdder) i still got iron sword :) 

![image](https://github.com/GC-spigot/AdvancedItems/assets/99331219/ccb589cb-9670-4088-b68f-6ed5c38059b8)

**Comment by ELIAS7281** [comment]
i can confirm leather armor is not working, using latest

**Comment by GC-spigot** [comment]
Looking into this!

**Comment by GC-spigot** [comment]
Fixed!
