### ISSUE TITLE
Disable word not working.

### ISSUE THREAD

**Issue by petrkeram** [GC-spigot/AdvancedItems#3]
Hello, we have a problem that if we set "disabled word" on any item, the item still works even in the forbidden world. I addressed this in ticket aitems-0050 and your colleagues told me I was right and to write it on github.

Here is my config for that item.
[Teleporter.yml_3.txt](https://github.com/GC-spigot/AdvancedItems/files/13178198/Teleporter.yml_3.txt)

**Comment by ELIAS7281** [comment]
i can confirm disabled worlds is not working.
using latest version

**Comment by GC-spigot** [comment]
Fixed!
