### ISSUE TITLE
Bug with the "INCREASE_DAMAGE" effect

### ISSUE THREAD

**Issue by Kleit02** [GC-spigot/AdvancedItems#56]
Hi, I have a problem with this effect.

I made an item that gives you a damage bonus when you have low health, the problem is that this error appears in the chat, I opened a ticket and they recommended me to report the bug on github.

Here are some images of the item, including its configuration and the error.
![Screenshot_3](https://github.com/user-attachments/assets/b515485b-c55b-4324-8e83-5e1f665df6fb)
![Screenshot_2](https://github.com/user-attachments/assets/264c78ab-e854-414a-a1e7-5f1b49beac04)
![Screenshot_1](https://github.com/user-attachments/assets/423eabc3-fe21-4d7d-9f56-8b72293121d4)

**Comment by HaydoPotato1310** [comment]
You are referencing the victim. You need to reference yourself, as you are increasing your own damage, not the victim's.
